name: PHP Composer

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./src

    - name: PHP Version Check
      run: php -v

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      working-directory: ./src

    - name: Generate key
      run: php artisan key:generate
      working-directory: ./src

    - name: Run PHP Mess Detector(PHPMD)
      run: ./vendor/bin/phpmd app --reportfile ./phpmd.result.xml xml ../.github/workflows/phpmd.ruleset.xml --ignore-violations-on-exit
      working-directory: ./src

    - name: Upload PHPMD File
      working-directory: ./src
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: phpmd.result.xml

