name: PHP Composer

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl
        ini-values: post_max_size=256M, short_open_tag=On
        coverage: xdebug
        tools: php-cs-fixer, phpunit

    - name: PHP Version Check
      run: php -v

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./src

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      working-directory: ./src

    - name: Generate key
      run: php artisan key:generate
      working-directory: ./src

    - name: Run PHP Mess Detector(PHPMD)
      run: ./vendor/bin/phpmd app --reportfile ./phpmd.result.xml xml ../.github/workflows/phpmd.ruleset.xml --ignore-violations-on-exit
      working-directory: ./src

    - name: Upload PHPMD File
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: ./src/phpmd.result.xml

    - name: Print PHPMD result
      shell: bash
      run: |
        value=`cat ./src/phpmd.result.xml`
        echo $value

    - name: Run PHP_CodeSniffer(PHPCS)
      run: ./vendor/bin/phpcs --report-file=./phpcs.result.xml --standard=../.github/workflows/phpcs.xml app || true
      working-directory: ./src

    - name: Upload PHPCS File
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: ./src/phpcs.result.xml

    - name: Print PHPCS result
      shell: bash
      run: |
        value=`cat ./src/phpcs.result.xml`
        echo $value

