name: PHP Composer

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: PHP Version Check
      run: php -v

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./src

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      working-directory: ./src

    - name: Generate key
      run: php artisan key:generate
      working-directory: ./src

  statistics:
    name: Statistics
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run PHP Mess Detector(PHPMD)
      run: ./vendor/bin/phpmd app --reportfile ./phpmd.result.xml xml ../.github/workflows/phpmd.ruleset.xml --ignore-violations-on-exit
      working-directory: ./src

    - name: Upload PHPMD File
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: ./src/phpmd.result.xml

    - name: Display PHPMD Results

  result:
    name: Result
    needs: statistics
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v1
        with:
          name: output
